"""Central configuration loaded from infra/.env.infra."""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from dotenv import load_dotenv

ENV_FILE = Path(__file__).parent / ".env.infra"
load_dotenv(ENV_FILE)


def _env(key: str, default: str | None = None, required: bool = False) -> str:
    value = os.environ.get(key, default)
    if required and not value:
        raise RuntimeError(f"Missing required config: {key} (set in {ENV_FILE})")
    return value or ""


@dataclass(frozen=True)
class Config:
    # Hetzner
    hcloud_token: str = field(default_factory=lambda: _env("HCLOUD_TOKEN", required=True))
    hcloud_server_type: str = field(default_factory=lambda: _env("HCLOUD_SERVER_TYPE", "cx23"))
    hcloud_location: str = field(default_factory=lambda: _env("HCLOUD_LOCATION", "nbg1"))
    hcloud_image: str = field(default_factory=lambda: _env("HCLOUD_IMAGE", "ubuntu-24.04"))
    server_name: str = field(default_factory=lambda: _env("HCLOUD_SERVER_NAME", "twitch-hub"))

    # SSH
    ssh_public_key_path: str = field(
        default_factory=lambda: _env("SSH_PUBLIC_KEY_PATH", str(Path.home() / ".ssh" / "id_ed25519.pub"))
    )

    # App
    app_domain: str = field(default_factory=lambda: _env("APP_DOMAIN", required=True))
    api_domain: str = field(default_factory=lambda: _env("API_DOMAIN", required=True))
    deploy_user: str = field(default_factory=lambda: _env("DEPLOY_USER", "deploy"))
    deploy_dir: str = field(default_factory=lambda: _env("DEPLOY_DIR", "/opt/twitch-hub"))
    acme_ca: str = field(default_factory=lambda: _env("ACME_CA", ""))

    # Twitch
    twitch_client_id: str = field(default_factory=lambda: _env("TWITCH_CLIENT_ID", required=True))
    twitch_client_secret: str = field(default_factory=lambda: _env("TWITCH_CLIENT_SECRET", required=True))

    # Secrets (generated by `run.py secrets`)
    postgres_user: str = field(default_factory=lambda: _env("POSTGRES_USER", "twitch_hub"))
    postgres_db: str = field(default_factory=lambda: _env("POSTGRES_DB", "twitch_hub"))
    postgres_password: str = field(default_factory=lambda: _env("POSTGRES_PASSWORD", required=True))
    redis_password: str = field(default_factory=lambda: _env("REDIS_PASSWORD", required=True))
    jwt_secret: str = field(default_factory=lambda: _env("JWT_SECRET", required=True))
    internal_api_secret: str = field(default_factory=lambda: _env("INTERNAL_API_SECRET", required=True))

    # GitHub Container Registry
    github_username: str = field(default_factory=lambda: _env("GITHUB_USERNAME", required=True))
    ghcr_token: str = field(default_factory=lambda: _env("GHCR_TOKEN", required=True))

    # Webhook deploy secret (auto-generated)
    webhook_secret: str = field(default_factory=lambda: _env("WEBHOOK_SECRET", ""))

    # Namecheap DNS (optional — enables auto-DNS in wizard)
    namecheap_api_user: str = field(default_factory=lambda: _env("NAMECHEAP_API_USER", ""))
    namecheap_api_key: str = field(default_factory=lambda: _env("NAMECHEAP_API_KEY", ""))
    namecheap_domain: str = field(default_factory=lambda: _env("NAMECHEAP_DOMAIN", ""))

    # Optional services
    stripe_secret_key: str = field(default_factory=lambda: _env("STRIPE_SECRET_KEY", ""))
    stripe_webhook_secret: str = field(default_factory=lambda: _env("STRIPE_WEBHOOK_SECRET", ""))
    stripe_monthly_price_id: str = field(default_factory=lambda: _env("STRIPE_MONTHLY_PRICE_ID", ""))
    stripe_annual_price_id: str = field(default_factory=lambda: _env("STRIPE_ANNUAL_PRICE_ID", ""))
    stripe_credit_pack_price_id: str = field(default_factory=lambda: _env("STRIPE_CREDIT_PACK_PRICE_ID", ""))
    sentry_dsn: str = field(default_factory=lambda: _env("SENTRY_DSN", ""))
    public_sentry_dsn: str = field(default_factory=lambda: _env("PUBLIC_SENTRY_DSN", ""))
    sentry_auth_token: str = field(default_factory=lambda: _env("SENTRY_AUTH_TOKEN", ""))
    sentry_org: str = field(default_factory=lambda: _env("SENTRY_ORG", ""))
    sentry_project: str = field(default_factory=lambda: _env("SENTRY_PROJECT", ""))

    @property
    def namecheap_enabled(self) -> bool:
        return bool(self.namecheap_api_user and self.namecheap_api_key and self.namecheap_domain)

    @property
    def server_ip_file(self) -> Path:
        return Path(__file__).parent / ".server_ip"

    def get_server_ip(self) -> str:
        if not self.server_ip_file.exists():
            raise RuntimeError(f"Server IP not found at {self.server_ip_file}. Run 'python run.py create' first.")
        return self.server_ip_file.read_text().strip()

    def save_server_ip(self, ip: str) -> None:
        self.server_ip_file.write_text(ip + "\n")

    def validate(self) -> list[str]:
        """Return a list of config validation errors (empty = valid)."""
        errors: list[str] = []

        # Required fields
        if not self.hcloud_token:
            errors.append("HCLOUD_TOKEN is not set")
        elif not self.validate_hcloud_token(self.hcloud_token):
            errors.append("HCLOUD_TOKEN format is invalid (expected 64-char alphanumeric)")
        if not self.app_domain:
            errors.append("APP_DOMAIN is not set")
        elif not self.validate_domain(self.app_domain):
            errors.append(f"APP_DOMAIN '{self.app_domain}' is not a valid domain format")
        if not self.api_domain:
            errors.append("API_DOMAIN is not set")
        elif not self.validate_domain(self.api_domain):
            errors.append(f"API_DOMAIN '{self.api_domain}' is not a valid domain format")
        if not self.twitch_client_id:
            errors.append("TWITCH_CLIENT_ID is not set")
        if not self.twitch_client_secret:
            errors.append("TWITCH_CLIENT_SECRET is not set")
        if not self.github_username:
            errors.append("GITHUB_USERNAME is not set")
        if not self.ghcr_token:
            errors.append("GHCR_TOKEN is not set")

        # Secrets
        for name, value in [
            ("POSTGRES_PASSWORD", self.postgres_password),
            ("REDIS_PASSWORD", self.redis_password),
            ("JWT_SECRET", self.jwt_secret),
            ("INTERNAL_API_SECRET", self.internal_api_secret),
        ]:
            if not value:
                errors.append(f"{name} is not set (run 'python run.py secrets')")
            elif len(value) < 32:
                errors.append(f"{name} is too short ({len(value)} chars, minimum 32)")

        # Namecheap (all-or-nothing: if any field is set, all must be)
        nc_fields = {
            "NAMECHEAP_API_USER": self.namecheap_api_user,
            "NAMECHEAP_API_KEY": self.namecheap_api_key,
            "NAMECHEAP_DOMAIN": self.namecheap_domain,
        }
        nc_set = {k for k, v in nc_fields.items() if v}
        nc_missing = {k for k, v in nc_fields.items() if not v}
        if nc_set and nc_missing:
            errors.append(f"Partial Namecheap config: set {', '.join(sorted(nc_missing))} or remove all")
        if self.namecheap_enabled:
            if not self.app_domain.endswith(f".{self.namecheap_domain}") and self.app_domain != self.namecheap_domain:
                errors.append(f"APP_DOMAIN '{self.app_domain}' is not under NAMECHEAP_DOMAIN '{self.namecheap_domain}'")
            if not self.api_domain.endswith(f".{self.namecheap_domain}") and self.api_domain != self.namecheap_domain:
                errors.append(f"API_DOMAIN '{self.api_domain}' is not under NAMECHEAP_DOMAIN '{self.namecheap_domain}'")

        # SSH key
        ssh_path = Path(self.ssh_public_key_path).expanduser()
        if not ssh_path.exists():
            errors.append(f"SSH public key not found at {ssh_path}")

        return errors

    @staticmethod
    def validate_domain(domain: str) -> bool:
        """Check that a string looks like a valid domain name."""
        pattern = r"^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.[A-Za-z0-9-]{1,63})*\.[A-Za-z]{2,}$"
        return bool(re.match(pattern, domain))

    @staticmethod
    def validate_hcloud_token(token: str) -> bool:
        """Check that a Hetzner token has the expected format."""
        return bool(re.match(r"^[A-Za-z0-9]{64}$", token))
