"""Central configuration loaded from infra/.env.infra."""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

from dotenv import load_dotenv

ENV_FILE = Path(__file__).parent / ".env.infra"
load_dotenv(ENV_FILE)


def _env(key: str, default: str | None = None, required: bool = False) -> str:
    value = os.environ.get(key, default)
    if required and not value:
        raise RuntimeError(f"Missing required config: {key} (set in {ENV_FILE})")
    return value or ""


@dataclass(frozen=True)
class Config:
    # Hetzner
    hcloud_token: str = field(default_factory=lambda: _env("HCLOUD_TOKEN", required=True))
    hcloud_server_type: str = field(default_factory=lambda: _env("HCLOUD_SERVER_TYPE", "cx23"))
    hcloud_location: str = field(default_factory=lambda: _env("HCLOUD_LOCATION", "nbg1"))
    hcloud_image: str = field(default_factory=lambda: _env("HCLOUD_IMAGE", "ubuntu-24.04"))
    server_name: str = field(default_factory=lambda: _env("HCLOUD_SERVER_NAME", "twitch-hub"))

    # SSH
    ssh_public_key_path: str = field(
        default_factory=lambda: _env("SSH_PUBLIC_KEY_PATH", str(Path.home() / ".ssh" / "id_ed25519.pub"))
    )

    # App
    app_domain: str = field(default_factory=lambda: _env("APP_DOMAIN", required=True))
    api_domain: str = field(default_factory=lambda: _env("API_DOMAIN", required=True))
    deploy_user: str = field(default_factory=lambda: _env("DEPLOY_USER", "deploy"))
    deploy_dir: str = field(default_factory=lambda: _env("DEPLOY_DIR", "/opt/twitch-hub"))

    # Twitch
    twitch_client_id: str = field(default_factory=lambda: _env("TWITCH_CLIENT_ID", required=True))
    twitch_client_secret: str = field(default_factory=lambda: _env("TWITCH_CLIENT_SECRET", required=True))

    # Secrets (generated by `run.py secrets`)
    postgres_user: str = field(default_factory=lambda: _env("POSTGRES_USER", "twitch_hub"))
    postgres_db: str = field(default_factory=lambda: _env("POSTGRES_DB", "twitch_hub"))
    postgres_password: str = field(default_factory=lambda: _env("POSTGRES_PASSWORD", required=True))
    redis_password: str = field(default_factory=lambda: _env("REDIS_PASSWORD", required=True))
    jwt_secret: str = field(default_factory=lambda: _env("JWT_SECRET", required=True))
    internal_api_secret: str = field(default_factory=lambda: _env("INTERNAL_API_SECRET", required=True))

    # Optional services
    stripe_secret_key: str = field(default_factory=lambda: _env("STRIPE_SECRET_KEY", ""))
    stripe_webhook_secret: str = field(default_factory=lambda: _env("STRIPE_WEBHOOK_SECRET", ""))
    stripe_monthly_price_id: str = field(default_factory=lambda: _env("STRIPE_MONTHLY_PRICE_ID", ""))
    stripe_annual_price_id: str = field(default_factory=lambda: _env("STRIPE_ANNUAL_PRICE_ID", ""))
    stripe_credit_pack_price_id: str = field(default_factory=lambda: _env("STRIPE_CREDIT_PACK_PRICE_ID", ""))
    sentry_dsn: str = field(default_factory=lambda: _env("SENTRY_DSN", ""))
    public_sentry_dsn: str = field(default_factory=lambda: _env("PUBLIC_SENTRY_DSN", ""))
    sentry_auth_token: str = field(default_factory=lambda: _env("SENTRY_AUTH_TOKEN", ""))
    sentry_org: str = field(default_factory=lambda: _env("SENTRY_ORG", ""))
    sentry_project: str = field(default_factory=lambda: _env("SENTRY_PROJECT", ""))

    @property
    def server_ip_file(self) -> Path:
        return Path(__file__).parent / ".server_ip"

    def get_server_ip(self) -> str:
        if not self.server_ip_file.exists():
            raise RuntimeError(f"Server IP not found at {self.server_ip_file}. Run 'python run.py create' first.")
        return self.server_ip_file.read_text().strip()

    def save_server_ip(self, ip: str) -> None:
        self.server_ip_file.write_text(ip + "\n")

    def validate(self) -> list[str]:
        """Return a list of config validation errors (empty = valid)."""
        errors: list[str] = []

        if not self.hcloud_token:
            errors.append("HCLOUD_TOKEN is not set")
        if not self.app_domain:
            errors.append("APP_DOMAIN is not set")
        if not self.api_domain:
            errors.append("API_DOMAIN is not set")
        if not self.twitch_client_id:
            errors.append("TWITCH_CLIENT_ID is not set")
        if not self.twitch_client_secret:
            errors.append("TWITCH_CLIENT_SECRET is not set")
        if not self.postgres_password:
            errors.append("POSTGRES_PASSWORD is not set (run 'python run.py secrets')")
        if not self.redis_password:
            errors.append("REDIS_PASSWORD is not set (run 'python run.py secrets')")
        if not self.jwt_secret:
            errors.append("JWT_SECRET is not set (run 'python run.py secrets')")
        if not self.internal_api_secret:
            errors.append("INTERNAL_API_SECRET is not set (run 'python run.py secrets')")

        ssh_path = Path(self.ssh_public_key_path).expanduser()
        if not ssh_path.exists():
            errors.append(f"SSH public key not found at {ssh_path}")

        return errors
