"""Interactive first-time setup wizard for Twitch Hub production deployment."""

from __future__ import annotations

import secrets
import shutil
import subprocess
import sys
from pathlib import Path

from config import ENV_FILE

INFRA_DIR = Path(__file__).parent


def _check_command(cmd: str) -> bool:
    """Check if a command is available on PATH."""
    return shutil.which(cmd) is not None


def _prompt(label: str, default: str = "", required: bool = True) -> str:
    """Prompt the user for input with an optional default."""
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"  {label}{suffix}: ").strip() or default
        if value or not required:
            return value
        print(f"  Error: {label} is required.")


def step_prerequisites() -> None:
    """Step 1: Check prerequisites."""
    print("\n=== Step 1/6: Checking prerequisites ===\n")
    checks = {
        "pyinfra": _check_command("pyinfra"),
        "hcloud": _check_command("hcloud"),
        "ssh-keygen": _check_command("ssh-keygen"),
    }

    all_ok = True
    for tool, found in checks.items():
        status = "OK" if found else "MISSING"
        print(f"  {tool}: {status}")
        if not found:
            all_ok = False

    ssh_key = Path.home() / ".ssh" / "id_ed25519.pub"
    if ssh_key.exists():
        print(f"  SSH key: OK ({ssh_key})")
    else:
        print(f"  SSH key: MISSING ({ssh_key})")
        print("  Hint: Generate one with: ssh-keygen -t ed25519")
        all_ok = False

    if not all_ok:
        print("\nPlease install missing prerequisites and re-run the wizard.")
        print("  pip install pyinfra hcloud")
        sys.exit(1)

    print("\n  All prerequisites satisfied.")


def step_collect_config() -> dict[str, str]:
    """Step 2: Collect configuration from user."""
    print("\n=== Step 2/6: Configuration ===\n")

    config: dict[str, str] = {}

    config["HCLOUD_TOKEN"] = _prompt("Hetzner Cloud API token")
    config["APP_DOMAIN"] = _prompt("App domain (e.g. twitchhub.example.com)")
    config["API_DOMAIN"] = _prompt("API domain (e.g. api.twitchhub.example.com)")
    config["GIT_REPO_URL"] = _prompt("Git repository URL")
    config["TWITCH_CLIENT_ID"] = _prompt("Twitch Client ID")
    config["TWITCH_CLIENT_SECRET"] = _prompt("Twitch Client Secret")

    # Optional
    config["SENTRY_DSN"] = _prompt("Sentry DSN (server, optional)", required=False)
    config["PUBLIC_SENTRY_DSN"] = _prompt("Sentry DSN (web, optional)", required=False)
    config["SENTRY_AUTH_TOKEN"] = _prompt("Sentry Auth Token (source map uploads, optional)", required=False)
    config["SENTRY_ORG"] = _prompt("Sentry Organization slug (optional)", required=False)
    config["SENTRY_PROJECT"] = _prompt("Sentry Project slug (optional)", required=False)
    config["STRIPE_SECRET_KEY"] = _prompt("Stripe Secret Key (optional)", required=False)

    return config


def step_generate_secrets(config: dict[str, str]) -> None:
    """Step 3: Generate secrets and write .env.infra."""
    print("\n=== Step 3/6: Generating secrets ===\n")

    config["POSTGRES_PASSWORD"] = secrets.token_urlsafe(24)
    config["REDIS_PASSWORD"] = secrets.token_urlsafe(24)
    config["JWT_SECRET"] = secrets.token_urlsafe(32)
    config["INTERNAL_API_SECRET"] = secrets.token_urlsafe(32)

    with open(ENV_FILE, "w") as f:
        f.write("# Twitch Hub Infrastructure Config (generated by wizard)\n\n")
        for key, value in config.items():
            if value:
                f.write(f"{key}={value}\n")

    print(f"  Wrote config to {ENV_FILE}")


def step_create_server() -> str:
    """Step 4: Create the Hetzner server."""
    print("\n=== Step 4/6: Creating Hetzner server ===\n")

    from config import Config
    from create_server import create_server

    cfg = Config()
    return create_server(cfg)


def step_dns_wait(ip: str) -> None:
    """Step 5: Prompt for DNS configuration and wait for propagation."""
    print("\n=== Step 5/6: DNS Configuration ===\n")

    from config import Config

    cfg = Config()

    print(f"  Point your DNS A records to: {ip}")
    print(f"    {cfg.app_domain} → {ip}")
    print(f"    {cfg.api_domain} → {ip}")
    print()

    input("  Press Enter when DNS records are configured...")

    from dns import wait_for_dns

    print("\n  Checking DNS propagation...")
    domains = [cfg.app_domain, cfg.api_domain]
    if wait_for_dns(domains, ip, timeout=300, interval=10):
        print("  DNS records verified!")
    else:
        print("  Warning: DNS not fully propagated yet. Continuing anyway...")
        print("  TLS certificates may fail until DNS resolves. You can re-run deploy later.")


def step_provision_and_deploy() -> None:
    """Step 6: Provision and deploy."""
    print("\n=== Step 6/6: Provisioning and deploying ===\n")

    from config import Config

    cfg = Config()
    ip = cfg.get_server_ip()

    print(f"==> Provisioning {ip} as root...")
    subprocess.run(
        ["pyinfra", "--user=root", ip, str(INFRA_DIR / "provision.py")],
        check=True,
    )

    print(f"\n==> Deploying to {ip} as {cfg.deploy_user}...")
    subprocess.run(
        ["pyinfra", f"--user={cfg.deploy_user}", ip, str(INFRA_DIR / "deploy.py")],
        check=True,
    )


def run_wizard() -> None:
    """Run the full interactive setup wizard."""
    print("=" * 50)
    print("  Twitch Hub — Production Setup Wizard")
    print("=" * 50)

    try:
        step_prerequisites()
        config = step_collect_config()
        step_generate_secrets(config)
        ip = step_create_server()
        step_dns_wait(ip)
        step_provision_and_deploy()
    except KeyboardInterrupt:
        print("\n\nWizard cancelled by user.")
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print(f"\n  Error: Command failed with exit code {e.returncode}")
        print(f"  Command: {e.cmd}")
        print("\n  Fix the issue above and re-run: python run.py wizard")
        sys.exit(1)
    except Exception as e:
        print(f"\n  Error: {e}")
        print("\n  If this is unexpected, check your config in .env.infra")
        print("  Re-run: python run.py wizard")
        sys.exit(1)

    from config import Config

    cfg = Config()
    print("\n" + "=" * 50)
    print("  Deployment complete!")
    print("=" * 50)
    print(f"\n  App: https://{cfg.app_domain}")
    print(f"  API: https://{cfg.api_domain}")
    print(f"  Server IP: {ip}")
    print()


if __name__ == "__main__":
    run_wizard()
